# coding: utf-8

"""
    Energy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Auction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auction_id': 'str',
        'users': 'list[str]',
        'total_incentive': 'int',
        'watt_hour_goal_saving': 'int',
        'bid_start_timestamp': 'int',
        'bid_end_timestamp': 'int',
        'off_start_timestamp': 'int',
        'off_end_timestamp': 'int'
    }

    attribute_map = {
        'auction_id': 'auctionId',
        'users': 'users',
        'total_incentive': 'totalIncentive',
        'watt_hour_goal_saving': 'wattHourGoalSaving',
        'bid_start_timestamp': 'bidStartTimestamp',
        'bid_end_timestamp': 'bidEndTimestamp',
        'off_start_timestamp': 'offStartTimestamp',
        'off_end_timestamp': 'offEndTimestamp'
    }

    def __init__(self, auction_id=None, users=None, total_incentive=None, watt_hour_goal_saving=None, bid_start_timestamp=None, bid_end_timestamp=None, off_start_timestamp=None, off_end_timestamp=None):  # noqa: E501
        """Auction - a model defined in Swagger"""  # noqa: E501

        self._auction_id = None
        self._users = None
        self._total_incentive = None
        self._watt_hour_goal_saving = None
        self._bid_start_timestamp = None
        self._bid_end_timestamp = None
        self._off_start_timestamp = None
        self._off_end_timestamp = None
        self.discriminator = None

        if auction_id is not None:
            self.auction_id = auction_id
        if users is not None:
            self.users = users
        if total_incentive is not None:
            self.total_incentive = total_incentive
        if watt_hour_goal_saving is not None:
            self.watt_hour_goal_saving = watt_hour_goal_saving
        if bid_start_timestamp is not None:
            self.bid_start_timestamp = bid_start_timestamp
        if bid_end_timestamp is not None:
            self.bid_end_timestamp = bid_end_timestamp
        if off_start_timestamp is not None:
            self.off_start_timestamp = off_start_timestamp
        if off_end_timestamp is not None:
            self.off_end_timestamp = off_end_timestamp

    @property
    def auction_id(self):
        """Gets the auction_id of this Auction.  # noqa: E501


        :return: The auction_id of this Auction.  # noqa: E501
        :rtype: str
        """
        return self._auction_id

    @auction_id.setter
    def auction_id(self, auction_id):
        """Sets the auction_id of this Auction.


        :param auction_id: The auction_id of this Auction.  # noqa: E501
        :type: str
        """

        self._auction_id = auction_id

    @property
    def users(self):
        """Gets the users of this Auction.  # noqa: E501


        :return: The users of this Auction.  # noqa: E501
        :rtype: list[str]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this Auction.


        :param users: The users of this Auction.  # noqa: E501
        :type: list[str]
        """

        self._users = users

    @property
    def total_incentive(self):
        """Gets the total_incentive of this Auction.  # noqa: E501


        :return: The total_incentive of this Auction.  # noqa: E501
        :rtype: int
        """
        return self._total_incentive

    @total_incentive.setter
    def total_incentive(self, total_incentive):
        """Sets the total_incentive of this Auction.


        :param total_incentive: The total_incentive of this Auction.  # noqa: E501
        :type: int
        """

        self._total_incentive = total_incentive

    @property
    def watt_hour_goal_saving(self):
        """Gets the watt_hour_goal_saving of this Auction.  # noqa: E501


        :return: The watt_hour_goal_saving of this Auction.  # noqa: E501
        :rtype: int
        """
        return self._watt_hour_goal_saving

    @watt_hour_goal_saving.setter
    def watt_hour_goal_saving(self, watt_hour_goal_saving):
        """Sets the watt_hour_goal_saving of this Auction.


        :param watt_hour_goal_saving: The watt_hour_goal_saving of this Auction.  # noqa: E501
        :type: int
        """

        self._watt_hour_goal_saving = watt_hour_goal_saving

    @property
    def bid_start_timestamp(self):
        """Gets the bid_start_timestamp of this Auction.  # noqa: E501


        :return: The bid_start_timestamp of this Auction.  # noqa: E501
        :rtype: int
        """
        return self._bid_start_timestamp

    @bid_start_timestamp.setter
    def bid_start_timestamp(self, bid_start_timestamp):
        """Sets the bid_start_timestamp of this Auction.


        :param bid_start_timestamp: The bid_start_timestamp of this Auction.  # noqa: E501
        :type: int
        """

        self._bid_start_timestamp = bid_start_timestamp

    @property
    def bid_end_timestamp(self):
        """Gets the bid_end_timestamp of this Auction.  # noqa: E501


        :return: The bid_end_timestamp of this Auction.  # noqa: E501
        :rtype: int
        """
        return self._bid_end_timestamp

    @bid_end_timestamp.setter
    def bid_end_timestamp(self, bid_end_timestamp):
        """Sets the bid_end_timestamp of this Auction.


        :param bid_end_timestamp: The bid_end_timestamp of this Auction.  # noqa: E501
        :type: int
        """

        self._bid_end_timestamp = bid_end_timestamp

    @property
    def off_start_timestamp(self):
        """Gets the off_start_timestamp of this Auction.  # noqa: E501


        :return: The off_start_timestamp of this Auction.  # noqa: E501
        :rtype: int
        """
        return self._off_start_timestamp

    @off_start_timestamp.setter
    def off_start_timestamp(self, off_start_timestamp):
        """Sets the off_start_timestamp of this Auction.


        :param off_start_timestamp: The off_start_timestamp of this Auction.  # noqa: E501
        :type: int
        """

        self._off_start_timestamp = off_start_timestamp

    @property
    def off_end_timestamp(self):
        """Gets the off_end_timestamp of this Auction.  # noqa: E501


        :return: The off_end_timestamp of this Auction.  # noqa: E501
        :rtype: int
        """
        return self._off_end_timestamp

    @off_end_timestamp.setter
    def off_end_timestamp(self, off_end_timestamp):
        """Sets the off_end_timestamp of this Auction.


        :param off_end_timestamp: The off_end_timestamp of this Auction.  # noqa: E501
        :type: int
        """

        self._off_end_timestamp = off_end_timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Auction, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Auction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
