# coding: utf-8

"""
    Energy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.auction_api import AuctionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuctionApi(unittest.TestCase):
    """AuctionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.auction_api.AuctionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_close_auction(self):
        """Test case for close_auction

        """
        pass

    def test_close_auction_pledge(self):
        """Test case for close_auction_pledge

        """
        pass

    def test_create_auction(self):
        """Test case for create_auction

        Create auction  # noqa: E501
        """
        pass

    def test_create_bid(self):
        """Test case for create_bid

        Create bid  # noqa: E501
        """
        pass

    def test_get_auction(self):
        """Test case for get_auction

        """
        pass

    def test_get_bids(self):
        """Test case for get_bids

        """
        pass

    def test_get_winning_bids(self):
        """Test case for get_winning_bids

        """
        pass


if __name__ == '__main__':
    unittest.main()
