# coding: utf-8

"""
    Energy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.device_api import DeviceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.device_api.DeviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_device_usage(self):
        """Test case for get_device_usage

        """
        pass

    def test_log_usage_stats(self):
        """Test case for log_usage_stats

        logUsageStats  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
